import { button, click, phase, latest, snapshot, lockedSpec, until } from "./workflow-discovery";
import { api } from "../../apps/desktop/src/lib/api";

declare global { var workflowRecoveryRecovered: typeof workflowDiscoveryRecovered; }

globalThis.workflowRecoveryRecovered = async (checkpoint) => {
  await globalThis.workflowDiscoveryRecovered(checkpoint);
  const initial = await latest();
  await window.workflowFixture.action("reset", "normal");
  await click("Retry");
  await phase("pending");
  await window.workflowFixture.action("releaseLaunch");
  await phase("running");
  await until(async () => (await snapshot()).skillLoads === 5, "retry Skill load");
  await click("Stop");
  await phase("aborted");
  lockedSpec();
  const stopped = await latest();
  if (stopped.id === initial.id || !stopped.turnId) throw new Error("Retry did not create a new bound attempt");
  await window.workflowFixture.action("reset", "normal");
  await click("Retry");
  await phase("pending");
  await window.workflowFixture.action("releaseLaunch");
  await phase("running");
  await window.workflowFixture.action("releaseProvider");
  await phase("normal");
  const success = await latest();
  await window.workflowFixture.action("reset", "failure");
  await click("Continue");
  await phase("pending");
  await window.workflowFixture.action("releaseLaunch");
  await phase("running");
  await window.workflowFixture.action("releaseProvider");
  await phase("failed");
  lockedSpec();
  if (button("Continue")) throw new Error("A failed continuation retained successful confirmation eligibility");
  const failed = await latest();
  if (failed.id === success.id) throw new Error("Continuation rebound the preceding attempt");
  await window.workflowFixture.action("reset", "cancelFailure");
  await click("Retry");
  await phase("pending");
  await window.workflowFixture.action("releaseLaunch");
  await phase("running");
  await click("Stop");
  await until(() => document.querySelector('.workflow-discovery [role="alert"]'), "observable cancellation failure");
  if (!(await latest()).turnId || (await latest()).phase !== "running" || button("Retry")) throw new Error("Failed cancellation falsely released ownership");
  await window.workflowFixture.action("releaseProvider");
  await phase("aborted");
  const retired = await latest();
  await window.workflowFixture.action("reset", "mismatched");
  await click("Retry");
  await phase("pending");
  await window.workflowFixture.action("releaseLaunch");
  const unresolved = await until(async () => { const attempt = await latest(); return attempt.uncertainAdmission && attempt.phase === "pending" && attempt.turnId ? attempt : null; }, "mismatched acknowledgement retains the admitted turn");
  if (button("Retry") || button("Continue")) throw new Error("A mismatched acknowledgement released workflow ownership");
  await window.workflowFixture.action("releaseProvider");
  await phase("normal");
  const reconciled = await latest();
  if (reconciled.id !== unresolved.id || reconciled.turnId !== unresolved.turnId) throw new Error("Reconciliation rebound the original attempt");
  await window.workflowFixture.action("reset", "normal");
  await window.workflowFixture.action("releaseLaunch");
  const ordinary = await window.workflowFixture.action("ordinaryPrompt", { sessionId: failed.sessionId, content: "Ordinary subsequent chat" }) as { turnId: string };
  await api.stopWorkflowExecution(retired.id);
  const afterStop = await latest();
  if (afterStop.phase !== "normal" || afterStop.id !== reconciled.id || !ordinary.turnId) throw new Error("Stale Stop changed an unrelated ordinary turn");
  await window.workflowFixture.action("releaseProvider");
  return { ok: true, restartInterrupted: true, promptCount: (await snapshot()).prompts, skillLoads: (await snapshot()).skillLoads, specStayedLocked: true, recovery: true };
};

