/**
 * The bootstrap script the desktop uploads over SSH (spec §5.2 step 2, §3.4).
 *
 * The script is the only artifact that runs on the remote machine. It downloads
 * the bundle the desktop pinned, verifies it against the digest the desktop
 * read from the published `.sha256`, installs it under the user's home, starts
 * `pi-host` on loopback with a single-use pairing token, and echoes the two
 * machine-readable lines the desktop parses.
 *
 * Two properties matter and both are tested:
 *
 * - The pairing token only ever lands in a `umask 077` file inside the
 *   bootstrap work directory on the remote machine, and on stdout of the SSH
 *   channel. It is never written to a world-readable path and never appears in
 *   a URL (security §3.4).
 * - Every failure exits non-zero with a `PI_HOST_BOOTSTRAP_FAILED <step>` line
 *   so the desktop can report a typed error instead of a bare exit code.
 *
 * Inputs are interpolated as single-quoted shell literals by
 * {@link shellQuote}; callers never build the script from untrusted text.
 */

export type PiHostBootstrapScriptInput = {
  /** Desktop version; the bundle must exist for this tag. */
  version: string;
  /** Asset URL on GitHub Releases. */
  artifactUrl: string;
  /** Tarball file name, e.g. `pi-host-0.15.1-beta.5-linux-x64.tar.gz`. */
  artifactName: string;
  /** Unpacked directory name, e.g. `pi-host-0.15.1-beta.5-linux-x64`. */
  bundleDir: string;
  /** Lower-case hex digest from the published `.sha256`. */
  expectedSha256: string;
  /** Loopback port for `pi-host`; `0` lets it pick a free port and report it. */
  port: number;
  /** Pairing token lifetime handed to `--pairing-lifetime-ms`. */
  pairingLifetimeMs: number;
  /** How long the script waits for the ready and pairing lines. */
  readyTimeoutSec: number;
};

/** Smallest Node major the bundle is built for (`bundle.mjs --target=node22`). */
const MIN_NODE_MAJOR = 22;

/** POSIX-safe single-quoted literal; `'` becomes `'\''`. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
/** Script variables in declaration order; the template interpolates the block. */
const SCRIPT_VARIABLES = [
  "VERSION",
  "ARTIFACT_URL",
  "ARTIFACT_NAME",
  "BUNDLE_DIR",
  "EXPECTED_SHA256",
  "PORT",
  "PAIRING_LIFETIME_MS",
  "READY_TIMEOUT_SEC",
  "MIN_NODE_MAJOR",
] as const;

export function buildBootstrapScript(input: PiHostBootstrapScriptInput): string {
  const values: string[] = [
    input.version,
    input.artifactUrl,
    input.artifactName,
    input.bundleDir,
    input.expectedSha256,
    String(input.port),
    String(input.pairingLifetimeMs),
    String(input.readyTimeoutSec),
    String(MIN_NODE_MAJOR),
  ];
  const assignments = SCRIPT_VARIABLES.map(
    (name, index) => `${name}=${shellQuote(values[index] ?? "")}`,
  ).join("\n");

  return `#!/bin/sh
# pi-host bootstrap — generated by PI-Desktop. Idempotent: it replaces the
# bundle for its own version, restarts the host it previously started, and
# prints a fresh single-use pairing token.
set -eu
umask 077

${assignments}

step() { printf '%s\\n' "PI_HOST_BOOTSTRAP $1"; }
die() {
  printf '%s\\n' "PI_HOST_BOOTSTRAP_FAILED $1" >&2
  printf '%s\\n' "PI_HOST_FAILED {\\"code\\":\\"HOST_BOOTSTRAP_FAILED\\",\\"step\\":\\"$1\\"}"
  exit 1
}

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing-$1"
}

[ -n "\${HOME:-}" ] || die "no-home"

need node
need tar

node_major=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || printf '0')
[ "$node_major" -ge "$MIN_NODE_MAJOR" ] 2>/dev/null || die "node-too-old"

work="$HOME/.pi-desktop/pi-host/.bootstrap"
mkdir -p "$work"
chmod 700 "$work" 2>/dev/null || die "bootstrap-permissions"
log="$work/pi-host.log"
err="$work/pi-host.err"
pidfile="$work/pi-host.pid"
: > "$log"
: > "$err"

# --- download the pinned bundle -------------------------------------------
step "download"
http_get() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --max-time 600 -o "$2" "$1"
  elif command -v wget >/dev/null 2>&1; then
    wget -q --timeout=600 -O "$2" "$1"
  else
    return 127
  fi
}

tarball="$work/$ARTIFACT_NAME"
rm -f "$tarball"
http_get "$ARTIFACT_URL" "$tarball" || die "download-failed"
chmod 600 "$tarball" 2>/dev/null || die "artifact-permissions"

# --- verify the published digest ------------------------------------------
step "verify"
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d ' ' -f 1
  else
    return 127
  fi
}
actual_sha256=$(sha256_of "$tarball") || die "missing-sha256-tool"
[ "$actual_sha256" = "$EXPECTED_SHA256" ] || die "checksum-mismatch"

# --- install under the user's home ----------------------------------------
step "install"
unpack="$work/unpack"
rm -rf "$unpack"
mkdir -p "$unpack"
tar -xzf "$tarball" -C "$unpack" || die "extract-failed"
[ -d "$unpack/$BUNDLE_DIR" ] || die "unexpected-archive-layout"
sh "$unpack/$BUNDLE_DIR/install.sh" >/dev/null || die "install-failed"

# --- (re)start on loopback with a fresh pairing token ----------------------
step "start"
if [ -f "$pidfile" ]; then
  previous=$(cat "$pidfile" 2>/dev/null || true)
  # The pidfile is never removed, so a recycled PID could name an unrelated
  # process owned by the same user. Only signal it when it is still our
  # pi-host; anything else is left alone.
  if [ -n "$previous" ] && kill -0 "$previous" 2>/dev/null && \\
     ps -p "$previous" -o command= 2>/dev/null | grep -q 'pi-host.js'; then
    kill "$previous" 2>/dev/null || true
    waited=0
    while kill -0 "$previous" 2>/dev/null && [ "$waited" -lt 10 ]; do
      sleep 1
      waited=$((waited + 1))
    done
  fi
fi

nohup node "$HOME/.pi-desktop/pi-host/current/pi-host.js" \\
  --port "$PORT" \\
  --pair \\
  --pairing-lifetime-ms "$PAIRING_LIFETIME_MS" \\
  >"$log" 2>"$err" </dev/null &
host_pid=$!
printf '%s\\n' "$host_pid" > "$pidfile"

# --- wait for the ready and pairing lines ---------------------------------
step "await-ready"
waited=0
while [ "$waited" -lt "$READY_TIMEOUT_SEC" ]; do
  if grep -q '^PI_HOST_FAILED ' "$log" 2>/dev/null; then
    printf '%s\\n' "PI_HOST_FAILED {\\"code\\":\\"HOST_BOOTSTRAP_FAILED\\",\\"step\\":\\"host-start-failed\\"}"
    exit 1
  fi
  ready=$(grep -m1 '^PI_HOST_READY ' "$log" 2>/dev/null || true)
  token=$(grep -m1 '^PI_HOST_PAIRING_TOKEN ' "$log" 2>/dev/null || true)
  if [ -n "$ready" ] && [ -n "$token" ]; then
    printf '%s\\n' "$ready"
    printf '%s\\n' "$token"
    step "ok"
    exit 0
  fi
  if ! kill -0 "$host_pid" 2>/dev/null; then
    printf '%s\\n' "PI_HOST_FAILED {\\"code\\":\\"HOST_BOOTSTRAP_FAILED\\",\\"step\\":\\"host-exited\\"}"
    exit 1
  fi
  sleep 1
  waited=$((waited + 1))
done
die "ready-timeout"
`;
}

// ---------------------------------------------------------------------------
// Output parsing
// ---------------------------------------------------------------------------

export type PiHostReadyLine = {
  hostId: string;
  host: string;
  port: number;
  version: string;
};

export type PiHostPairingLine = {
  token: string;
  expiresAt: number;
};

export type PiHostBootstrapOutput = {
  ready: PiHostReadyLine | null;
  pairing: PiHostPairingLine | null;
  /** `PI_HOST_BOOTSTRAP <step>` progress lines, in order. */
  steps: string[];
  /** The `step` a `PI_HOST_FAILED` line reported, when the script failed. */
  failure: string | null;
};

function parseJsonObject(line: string, prefix: string): Record<string, unknown> | null {
  if (!line.startsWith(prefix)) return null;
  try {
    const parsed: unknown = JSON.parse(line.slice(prefix.length));
    return typeof parsed === "object" && parsed !== null
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

/**
 * Read the bootstrap script's stdout. The script owns the format; this parser
 * is deliberately tolerant about interleaved progress lines and hostile about
 * missing fields, so a truncated channel cannot yield a half-built host.
 */
export function parseBootstrapOutput(stdout: string): PiHostBootstrapOutput {
  const output: PiHostBootstrapOutput = {
    ready: null,
    pairing: null,
    steps: [],
    failure: null,
  };

  for (const raw of stdout.split("\n")) {
    const line = raw.trim();
    if (!line) continue;

    if (line.startsWith("PI_HOST_BOOTSTRAP_FAILED ")) {
      if (!output.failure) output.failure = line.slice("PI_HOST_BOOTSTRAP_FAILED ".length).trim();
      continue;
    }
    if (line.startsWith("PI_HOST_BOOTSTRAP ")) {
      const step = line.slice("PI_HOST_BOOTSTRAP ".length).trim();
      if (step) output.steps.push(step);
      continue;
    }
    if (line.startsWith("PI_HOST_FAILED ")) {
      const payload = parseJsonObject(line, "PI_HOST_FAILED ");
      const code = payload?.code === "HOST_BOOTSTRAP_FAILED" ? payload.step : undefined;
      if (typeof code === "string" && !output.failure) output.failure = code;
      continue;
    }
    const ready = parseJsonObject(line, "PI_HOST_READY ");
    if (ready) {
      const { hostId, host, port, version } = ready;
      if (
        typeof hostId === "string" &&
        hostId.length > 0 &&
        typeof host === "string" &&
        typeof port === "number" &&
        Number.isInteger(port) &&
        port > 0 &&
        typeof version === "string"
      ) {
        output.ready = { hostId, host, port, version };
      }
      continue;
    }
    const pairing = parseJsonObject(line, "PI_HOST_PAIRING_TOKEN ");
    if (pairing) {
      const { token, expiresAt } = pairing;
      if (typeof token === "string" && token.length > 0) {
        output.pairing = {
          token,
          expiresAt: typeof expiresAt === "number" ? expiresAt : 0,
        };
      }
    }
  }

  return output;
}

/**
 * Replace the single-use pairing token in the script's stdout before it
 * reaches a log or an error payload. The token is only expected on stdout on
 * the success path, but a diagnostic that leaks a live token is worse than no
 * diagnostic at all.
 */
export function redactBootstrapOutput(stdout: string): string {
  return stdout
    .split("\n")
    .map((line) =>
      line.startsWith("PI_HOST_PAIRING_TOKEN ") ? "PI_HOST_PAIRING_TOKEN <redacted>" : line,
    )
    .join("\n");
}
