export type AppError = {
  code: string;
  message: string;
  details?: unknown;
  retriable?: boolean;
  causeCode?: string;
  traceId?: string;
};

export type Result<T> =
  | { ok: true; data: T }
  | { ok: false; error: AppError };

export function ok<T>(data: T): Result<T> {
  return { ok: true, data };
}

export function err<T = never>(
  code: string,
  message: string,
  extra?: Partial<AppError>,
): Result<T> {
  return {
    ok: false,
    error: { code, message, ...extra },
  };
}

export const ErrorCodes = {
  PROTOCOL_MISMATCH: "PROTOCOL_MISMATCH",
  HOST_UNAVAILABLE: "HOST_UNAVAILABLE",
  HOST_OVERLOADED: "HOST_OVERLOADED",
  AGENT_UNAVAILABLE: "AGENT_UNAVAILABLE",
  APP_DEGRADED: "APP_DEGRADED",
  INTERNAL: "INTERNAL",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TIMEOUT: "TIMEOUT",
  NETWORK_ERROR: "NETWORK_ERROR",
  AGENT_BUSY: "AGENT_BUSY",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  TURN_NOT_FOUND: "TURN_NOT_FOUND",
  TURN_ABORTED: "TURN_ABORTED",
  MODEL_NOT_CONFIGURED: "MODEL_NOT_CONFIGURED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PROVIDER_UNAUTHORIZED: "PROVIDER_UNAUTHORIZED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  PROVIDER_SECRET_MISSING: "PROVIDER_SECRET_MISSING",
  CONTEXT_TOO_LARGE: "CONTEXT_TOO_LARGE",
  STREAM_FAILED: "STREAM_FAILED",
  PROMPT_ENHANCEMENT_EMPTY: "PROMPT_ENHANCEMENT_EMPTY",
  SUBAGENT_IDLE_TIMEOUT: "SUBAGENT_IDLE_TIMEOUT",
  SUBAGENT_DURATION_TIMEOUT: "SUBAGENT_DURATION_TIMEOUT",
  WORKSPACE_REQUIRED: "WORKSPACE_REQUIRED",
  PATH_OUTSIDE_WORKSPACE: "PATH_OUTSIDE_WORKSPACE",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_DENIED: "TOOL_DENIED",
  TOOL_TIMEOUT: "TOOL_TIMEOUT",
  TOOL_FAILED: "TOOL_FAILED",
  /**
   * The mutation recovery guard stopped the turn after repeated same-path Edit
   * or patch-command failures (spec 18-line-anchored-edit-contract §9.3). Retriable: the user may continue.
   */
  MUTATION_RETRY_BUDGET_EXHAUSTED: "MUTATION_RETRY_BUDGET_EXHAUSTED",
  PROCESS_RESOURCE_EXHAUSTED: "PROCESS_RESOURCE_EXHAUSTED",
  TOOL_ABORTED: "TOOL_ABORTED",
  COMMAND_SHELL_CHANGED: "COMMAND_SHELL_CHANGED",
  SHELL_NOT_FOUND: "SHELL_NOT_FOUND",
  COMMAND_SHELL_INVALID: "COMMAND_SHELL_INVALID",
  PERMISSION_TIMEOUT: "PERMISSION_TIMEOUT",
  PERMISSION_REQUIRED: "PERMISSION_REQUIRED",
  BASH_DISABLED_IN_CHAT: "BASH_DISABLED_IN_CHAT",
  WRITE_DISABLED_IN_CHAT: "WRITE_DISABLED_IN_CHAT",
  WRITE_DISABLED_IN_PLAN: "WRITE_DISABLED_IN_PLAN",
  EDIT_DISABLED_IN_PLAN: "EDIT_DISABLED_IN_PLAN",
  PLUGIN_DISABLED_IN_PLAN: "PLUGIN_DISABLED_IN_PLAN",
  TOOL_DISABLED_IN_PLAN: "TOOL_DISABLED_IN_PLAN",
  PLAN_NOT_ACTIVE: "PLAN_NOT_ACTIVE",
  /** SubmitPlan in Goal mode, or SubmitGoal in Plan mode (D198). */
  PLAN_KIND_MISMATCH: "PLAN_KIND_MISMATCH",
  PLAN_REQUIRES_INTERACTIVE_SESSION: "PLAN_REQUIRES_INTERACTIVE_SESSION",
  PLAN_INVALID_ARGUMENT: "PLAN_INVALID_ARGUMENT",
  PLAN_SUBMIT_FAILED: "PLAN_SUBMIT_FAILED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_ALREADY_PENDING: "PLAN_ALREADY_PENDING",
  PLAN_ALREADY_RESOLVED: "PLAN_ALREADY_RESOLVED",
  PLAN_APPROVAL_REQUIRED: "PLAN_APPROVAL_REQUIRED",
  PLAN_APPROVAL_STALE: "PLAN_APPROVAL_STALE",
  PLAN_APPROVAL_TIMEOUT: "PLAN_APPROVAL_TIMEOUT",
  PLAN_APPROVAL_INTERRUPTED: "PLAN_APPROVAL_INTERRUPTED",
  PLAN_REJECTED: "PLAN_REJECTED",
  PLAN_INVALID_ACTION: "PLAN_INVALID_ACTION",
  PLAN_PERMISSION_MODE_INVALID: "PLAN_PERMISSION_MODE_INVALID",
  PLAN_PERMISSION_MODE_REQUIRED: "PLAN_PERMISSION_MODE_REQUIRED",
  PLAN_APPROVAL_CONFLICT: "PLAN_APPROVAL_CONFLICT",
  PLAN_CONFIGURATION_BLOCKED: "PLAN_CONFIGURATION_BLOCKED",
  PLAN_MARKDOWN_TOO_LARGE: "PLAN_MARKDOWN_TOO_LARGE",
  PLAN_ARTIFACT_INVALID: "PLAN_ARTIFACT_INVALID",
  PLAN_ARTIFACT_PATH_UNSAFE: "PLAN_ARTIFACT_PATH_UNSAFE",
  PLAN_ARTIFACT_WRITE_FAILED: "PLAN_ARTIFACT_WRITE_FAILED",
  PLAN_ARTIFACT_COLLISION_LIMIT: "PLAN_ARTIFACT_COLLISION_LIMIT",
  PLAN_ARTIFACT_NOT_READY: "PLAN_ARTIFACT_NOT_READY",
  PLAN_ARTIFACT_HASH_MISMATCH: "PLAN_ARTIFACT_HASH_MISMATCH",
  PLAN_EXECUTION_ACTIVE: "PLAN_EXECUTION_ACTIVE",
  PLAN_EXECUTION_NOT_FOUND: "PLAN_EXECUTION_NOT_FOUND",
  PLAN_EXECUTION_ALREADY_CLAIMED: "PLAN_EXECUTION_ALREADY_CLAIMED",
  PLAN_EXECUTION_STALE: "PLAN_EXECUTION_STALE",
  PLAN_EXECUTION_STATUS_INVALID: "PLAN_EXECUTION_STATUS_INVALID",
  PLAN_EXECUTION_CONFLICT: "PLAN_EXECUTION_CONFLICT",
  PLAN_EXECUTION_FAILED: "PLAN_EXECUTION_FAILED",
  PLAN_EXECUTION_INTERRUPTED: "PLAN_EXECUTION_INTERRUPTED",
  PLUGIN_INVALID: "PLUGIN_INVALID",
  PLUGIN_LOAD_FAILED: "PLUGIN_LOAD_FAILED",
} as const;
