export type AppError = {
  code: string;
  message: string;
  details?: unknown;
  retriable?: boolean;
  causeCode?: string;
  traceId?: string;
};

export type Result<T> =
  | { ok: true; data: T }
  | { ok: false; error: AppError };

export function ok<T>(data: T): Result<T> {
  return { ok: true, data };
}

export function err<T = never>(
  code: string,
  message: string,
  extra?: Partial<AppError>,
): Result<T> {
  return {
    ok: false,
    error: { code, message, ...extra },
  };
}

export const ErrorCodes = {
  PROTOCOL_MISMATCH: "PROTOCOL_MISMATCH",
  HOST_UNAVAILABLE: "HOST_UNAVAILABLE",
  HOST_OVERLOADED: "HOST_OVERLOADED",
  AGENT_UNAVAILABLE: "AGENT_UNAVAILABLE",
  APP_DEGRADED: "APP_DEGRADED",
  INTERNAL: "INTERNAL",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TIMEOUT: "TIMEOUT",
  NETWORK_ERROR: "NETWORK_ERROR",
  AGENT_BUSY: "AGENT_BUSY",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  TURN_NOT_FOUND: "TURN_NOT_FOUND",
  TURN_ABORTED: "TURN_ABORTED",
  MODEL_NOT_CONFIGURED: "MODEL_NOT_CONFIGURED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PROVIDER_UNAUTHORIZED: "PROVIDER_UNAUTHORIZED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  PROVIDER_SECRET_MISSING: "PROVIDER_SECRET_MISSING",
  CONTEXT_TOO_LARGE: "CONTEXT_TOO_LARGE",
  STREAM_FAILED: "STREAM_FAILED",
  WORKSPACE_REQUIRED: "WORKSPACE_REQUIRED",
  PATH_OUTSIDE_WORKSPACE: "PATH_OUTSIDE_WORKSPACE",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_DENIED: "TOOL_DENIED",
  TOOL_TIMEOUT: "TOOL_TIMEOUT",
  TOOL_FAILED: "TOOL_FAILED",
  PROCESS_RESOURCE_EXHAUSTED: "PROCESS_RESOURCE_EXHAUSTED",
  PERMISSION_TIMEOUT: "PERMISSION_TIMEOUT",
  PERMISSION_REQUIRED: "PERMISSION_REQUIRED",
  BASH_DISABLED_IN_CHAT: "BASH_DISABLED_IN_CHAT",
  WRITE_DISABLED_IN_CHAT: "WRITE_DISABLED_IN_CHAT",
  PLUGIN_INVALID: "PLUGIN_INVALID",
  PLUGIN_LOAD_FAILED: "PLUGIN_LOAD_FAILED",
} as const;
