/**
 * The catalog that ships inside the app.
 *
 * It is the floor, not the ceiling: the market must be useful with the network
 * off and before any remote catalog exists, so every entry here is either
 * zero-config or asks for exactly one obvious value. Remote catalogs layer on
 * top later; this file stays the offline fallback.
 */
import type { McpCatalogFile } from "./mcp-catalog.js";

export const BUILTIN_MCP_CATALOG: McpCatalogFile = {
  schemaVersion: 1,
  updatedAt: "2026-09-12",
  source: "builtin",
  servers: [
    {
      id: "memory",
      name: "Memory",
      description: "持久知识图谱,让会话之间记住实体与关系",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
      categories: ["productivity"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-memory"],
      notes: "首次运行由 npx 拉包,稍等片刻",
    },
    {
      id: "sequential-thinking",
      name: "Sequential Thinking",
      description: "动态反思式分步推理,复杂问题拆解",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
      categories: ["productivity"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    },
    {
      id: "everything",
      name: "Everything",
      description: "官方测试 server,覆盖全部 MCP 能力,用来验证接入是否正常",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
      categories: ["docs"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-everything"],
    },
    {
      id: "filesystem",
      name: "Filesystem",
      description: "在指定目录范围内读写文件、列目录、搜索",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
      categories: ["data"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-filesystem", "${MCP_FS_ROOT}"],
      requiredEnv: [
        {
          name: "MCP_FS_ROOT",
          description: "允许访问的根目录",
          defaultValue: "~",
        },
      ],
      notes: "server 只能访问该目录之内的路径",
    },
    {
      id: "playwright",
      name: "Playwright",
      description: "用可访问性树驱动浏览器:打开页面、点击、填表、截图",
      author: "microsoft",
      homepage: "https://github.com/microsoft/playwright-mcp",
      categories: ["web"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@playwright/mcp@latest"],
      prerequisites: ["首次使用会提示安装浏览器内核"],
    },
    {
      id: "context7",
      name: "Context7",
      description: "随时查到各框架/库的最新版文档,避免模型凭旧记忆写代码",
      author: "upstash",
      homepage: "https://github.com/upstash/context7",
      categories: ["docs"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@upstash/context7-mcp"],
    },
    {
      id: "fetch",
      name: "Fetch",
      description: "抓取网页并转成 Markdown 给模型阅读",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
      categories: ["web"],
      verified: true,
      transport: "stdio",
      command: "uvx",
      args: ["mcp-server-fetch"],
      prerequisites: ["需已安装 uv/uvx"],
    },
    {
      id: "git",
      name: "Git",
      description: "读取仓库状态、diff、log,并执行常用 Git 操作",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
      categories: ["devtools"],
      transport: "stdio",
      command: "uvx",
      args: ["mcp-server-git"],
      prerequisites: ["需已安装 uv/uvx"],
    },
    {
      id: "time",
      name: "Time",
      description: "查时区与时间换算",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
      categories: ["productivity"],
      transport: "stdio",
      command: "uvx",
      args: ["mcp-server-time"],
      prerequisites: ["需已安装 uv/uvx"],
    },
    {
      id: "serena",
      name: "Serena",
      description: "语义检索 + LSP 的代码理解工具集,大型仓库导航",
      author: "oraios",
      homepage: "https://github.com/oraios/serena",
      categories: ["devtools"],
      transport: "stdio",
      command: "uvx",
      args: [
        "--from",
        "git+https://github.com/oraios/serena",
        "serena",
        "start-mcp-server",
        "--context",
        "ide-assistant",
      ],
      prerequisites: ["需已安装 uv/uvx", "首次启动会克隆仓库,较慢"],
    },
    {
      id: "deepwiki",
      name: "DeepWiki",
      description: "问任何 GitHub 仓库的架构与实现,仓库百科",
      author: "devin",
      homepage: "https://deepwiki.com",
      categories: ["docs"],
      verified: true,
      transport: "http",
      url: "https://mcp.deepwiki.com/mcp",
    },
    {
      id: "notion",
      name: "Notion",
      description: "搜索、读取、创建 Notion 页面与数据库",
      author: "notion",
      homepage: "https://developers.notion.com/docs/mcp",
      categories: ["productivity"],
      verified: true,
      transport: "http",
      url: "https://mcp.notion.com/mcp",
      notes: "首次连接需在浏览器完成 Notion 授权",
    },
    {
      id: "exa",
      name: "Exa",
      description: "面向 AI 的网络搜索与网页内容获取",
      author: "exa",
      homepage: "https://docs.exa.ai/help/mcp",
      categories: ["web"],
      verified: true,
      transport: "http",
      url: "https://mcp.exa.ai/mcp",
    },
    {
      id: "github",
      name: "GitHub",
      description: "官方远程 MCP:仓库、issue、PR、Actions 操作",
      author: "github",
      homepage: "https://github.com/github/github-mcp-server",
      categories: ["devtools"],
      verified: true,
      transport: "http",
      url: "https://api.githubcopilot.com/mcp/",
      headers: { Authorization: "Bearer ${GITHUB_PAT}" },
      requiredEnv: [
        {
          name: "GITHUB_PAT",
          description: "GitHub Personal Access Token",
        },
      ],
    },
    {
      id: "brave-search",
      name: "Brave Search",
      description: "Brave 网络搜索",
      author: "modelcontextprotocol",
      homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
      categories: ["web"],
      verified: true,
      transport: "stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-brave-search"],
      env: { BRAVE_API_KEY: "${BRAVE_API_KEY}" },
      requiredEnv: [
        {
          name: "BRAVE_API_KEY",
          description: "Brave Search API Key",
        },
      ],
    },
  ],
};
