export const PROTOCOL_VERSION = 4 as const;
export const APP_NAME = "PI-Desktop";
export const APP_VERSION = "0.1.0";

export const IPC = {
  invoke: {
    appGetVersion: "pi-desktop/app/getVersion",
    appHealth: "pi-desktop/app/health",
    appGetOnboarding: "pi-desktop/app/getOnboarding",
    appDismissOnboarding: "pi-desktop/app/dismissOnboarding",
    notificationList: "pi-desktop/notification/list",
    notificationMarkRead: "pi-desktop/notification/markRead",
    notificationMarkAllRead: "pi-desktop/notification/markAllRead",
    notificationClear: "pi-desktop/notification/clear",
    notificationShowNative: "pi-desktop/notification/showNative",
    notificationSetViewingSession: "pi-desktop/notification/setViewingSession",
    agentPrompt: "pi-desktop/agent/prompt",
    agentAbort: "pi-desktop/agent/abort",
    agentGetStatus: "pi-desktop/agent/getStatus",
    sessionList: "pi-desktop/session/list",
    sessionCreate: "pi-desktop/session/create",
    sessionGet: "pi-desktop/session/get",
    sessionDelete: "pi-desktop/session/delete",
    sessionRename: "pi-desktop/session/rename",
    sessionConfigure: "pi-desktop/session/configure",
    sessionImportScan: "pi-desktop/session/importScan",
    sessionImportRun: "pi-desktop/session/importRun",
    sessionReplaceMessages: "pi-desktop/session/replaceMessages",
    sessionSaveRevision: "pi-desktop/session/saveRevision",
    sessionListRevisions: "pi-desktop/session/listRevisions",
    sessionActivateRevision: "pi-desktop/session/activateRevision",
    settingsGet: "pi-desktop/settings/get",
    settingsSet: "pi-desktop/settings/set",
    secretsSet: "pi-desktop/secrets/set",
    secretsDelete: "pi-desktop/secrets/delete",
    secretsHas: "pi-desktop/secrets/has",
    projectOpen: "pi-desktop/project/open",
    projectGet: "pi-desktop/project/get",
    projectList: "pi-desktop/project/list",
    projectSet: "pi-desktop/project/set",
    projectClear: "pi-desktop/project/clear",
    pullsList: "pi-desktop/pulls/list",
    scheduledList: "pi-desktop/scheduled/list",
    scheduledCreate: "pi-desktop/scheduled/create",
    scheduledUpdate: "pi-desktop/scheduled/update",
    scheduledDelete: "pi-desktop/scheduled/delete",
    scheduledRun: "pi-desktop/scheduled/run",
    toolResolvePermission: "pi-desktop/tool/resolvePermission",
    providersList: "pi-desktop/providers/list",
    providersCreate: "pi-desktop/providers/create",
    providersUpdate: "pi-desktop/providers/update",
    providersDelete: "pi-desktop/providers/delete",
    providersTest: "pi-desktop/providers/testConnection",
    providersListModels: "pi-desktop/providers/listModels",
    pluginList: "pi-desktop/plugin/list",
    pluginLoadDev: "pi-desktop/plugin/loadDev",
    pluginEnable: "pi-desktop/plugin/enable",
    pluginDisable: "pi-desktop/plugin/disable",
    pluginUninstall: "pi-desktop/plugin/uninstall",
    commandPaletteSearch: "pi-desktop/commandPalette/search",
    commandPaletteExecute: "pi-desktop/commandPalette/execute",
    logOpenFolder: "pi-desktop/log/openFolder",
    composerPickFiles: "pi-desktop/composer/pickFiles",
    composerPickPhotos: "pi-desktop/composer/pickPhotos",
    workspaceDiff: "pi-desktop/workspace/diff",
    terminalCreate: "pi-desktop/terminal/create",
    terminalWrite: "pi-desktop/terminal/write",
    terminalResize: "pi-desktop/terminal/resize",
    terminalDispose: "pi-desktop/terminal/dispose",
    browserNavigate: "pi-desktop/browser/navigate",
    browserAction: "pi-desktop/browser/action",
    browserSetBounds: "pi-desktop/browser/setBounds",
    browserSetVisible: "pi-desktop/browser/setVisible",
    browserOpenExternal: "pi-desktop/browser/openExternal",
    browserGetState: "pi-desktop/browser/getState",
    fsList: "pi-desktop/fs/list",
    fsRead: "pi-desktop/fs/read",
    fsReveal: "pi-desktop/fs/reveal",
    windowResizeBy: "pi-desktop/window/resizeBy",
  },
  event: {
    agentMessage: "pi-desktop/agent/event/message",
    hostStatus: "pi-desktop/app/event/hostStatus",
    toast: "pi-desktop/app/event/toast",
    terminalData: "pi-desktop/terminal/event/data",
    terminalExit: "pi-desktop/terminal/event/exit",
    browserState: "pi-desktop/browser/event/state",
    browserPreview: "pi-desktop/browser/event/preview",
    notificationChanged: "pi-desktop/notification/event/changed",
    notificationActivated: "pi-desktop/notification/event/activated",
  },
} as const;

export const IPC_WHITELIST = new Set<string>([
  ...Object.values(IPC.invoke),
  ...Object.values(IPC.event),
]);
