export const PROTOCOL_VERSION = 6 as const;
export const APP_ID = "com.pi-desktop.app";
export const APP_NAME = "PI-Desktop";
export const APP_VERSION = "0.2.11";

export const APP_MENU_COMMANDS = [
  "newTask",
  "openProject",
  "openSettings",
  "openSearch",
  "openCommandPalette",
  "toggleSidebar",
  "openHelp",
  "openLogs",
  "checkForUpdates",
] as const;

export type AppMenuCommand = (typeof APP_MENU_COMMANDS)[number];

export const NATIVE_MENU_ACTIONS = [
  "undo",
  "redo",
  "cut",
  "copy",
  "paste",
  "selectAll",
  "reload",
  "zoomIn",
  "zoomOut",
  "resetZoom",
  "toggleFullScreen",
  "minimize",
  "toggleMaximize",
  "close",
] as const;

export type NativeMenuAction = (typeof NATIVE_MENU_ACTIONS)[number];

export const WINDOW_CONTROL_ACTIONS = [
  "getState",
  "minimize",
  "toggleMaximize",
  "close",
] as const;

export type WindowControlAction = (typeof WINDOW_CONTROL_ACTIONS)[number];

export const IPC = {
  invoke: {
    appGetVersion: "pi-desktop/app/getVersion",
    appHealth: "pi-desktop/app/health",
    appGetOnboarding: "pi-desktop/app/getOnboarding",
    appDismissOnboarding: "pi-desktop/app/dismissOnboarding",
    updatesGetState: "pi-desktop/updates/getState",
    updatesCheck: "pi-desktop/updates/check",
    updatesDownload: "pi-desktop/updates/download",
    updatesInstall: "pi-desktop/updates/install",
    updatesOpenReleases: "pi-desktop/updates/openReleases",
    notificationList: "pi-desktop/notification/list",
    notificationMarkRead: "pi-desktop/notification/markRead",
    notificationMarkAllRead: "pi-desktop/notification/markAllRead",
    notificationClear: "pi-desktop/notification/clear",
    notificationShowNative: "pi-desktop/notification/showNative",
    notificationSetViewingSession: "pi-desktop/notification/setViewingSession",
    agentPrompt: "pi-desktop/agent/prompt",
    agentCompact: "pi-desktop/agent/compact",
    agentAbort: "pi-desktop/agent/abort",
    agentGetStatus: "pi-desktop/agent/getStatus",
    agentInstructionsGet: "pi-desktop/agent/instructions/get",
    agentInstructionsSave: "pi-desktop/agent/instructions/save",
    sessionList: "pi-desktop/session/list",
    sessionCreate: "pi-desktop/session/create",
    sessionFork: "pi-desktop/session/fork",
    sessionGet: "pi-desktop/session/get",
    sessionDelete: "pi-desktop/session/delete",
    sessionRename: "pi-desktop/session/rename",
    sessionConfigure: "pi-desktop/session/configure",
    sessionImportScan: "pi-desktop/session/importScan",
    sessionImportRun: "pi-desktop/session/importRun",
    sessionReplaceMessages: "pi-desktop/session/replaceMessages",
    sessionSaveRevision: "pi-desktop/session/saveRevision",
    sessionListRevisions: "pi-desktop/session/listRevisions",
    sessionActivateRevision: "pi-desktop/session/activateRevision",
    projectOpenFolder: "pi-desktop/project/openFolder",
    settingsGet: "pi-desktop/settings/get",
    settingsSet: "pi-desktop/settings/set",
    secretsSet: "pi-desktop/secrets/set",
    secretsDelete: "pi-desktop/secrets/delete",
    secretsHas: "pi-desktop/secrets/has",
    projectOpen: "pi-desktop/project/open",
    projectGet: "pi-desktop/project/get",
    projectList: "pi-desktop/project/list",
    projectSet: "pi-desktop/project/set",
    projectClear: "pi-desktop/project/clear",
    pullsList: "pi-desktop/pulls/list",
    scheduledList: "pi-desktop/scheduled/list",
    scheduledCreate: "pi-desktop/scheduled/create",
    scheduledUpdate: "pi-desktop/scheduled/update",
    scheduledDelete: "pi-desktop/scheduled/delete",
    scheduledRun: "pi-desktop/scheduled/run",
    toolResolvePermission: "pi-desktop/tool/resolvePermission",
    providersList: "pi-desktop/providers/list",
    providersCreate: "pi-desktop/providers/create",
    providersUpdate: "pi-desktop/providers/update",
    providersDelete: "pi-desktop/providers/delete",
    providersTest: "pi-desktop/providers/testConnection",
    providersListModels: "pi-desktop/providers/listModels",
    pluginList: "pi-desktop/plugin/list",
    pluginLoadDev: "pi-desktop/plugin/loadDev",
    pluginCreateFromTemplate: "pi-desktop/plugin/createFromTemplate",
    pluginInstallFromPath: "pi-desktop/plugin/installFromPath",
    pluginInstallFromPackage: "pi-desktop/plugin/installFromPackage",
    pluginEnable: "pi-desktop/plugin/enable",
    pluginDisable: "pi-desktop/plugin/disable",
    pluginUninstall: "pi-desktop/plugin/uninstall",
    pluginSetAutoUpdate: "pi-desktop/plugin/setAutoUpdate",
    pluginOpenPanel: "pi-desktop/plugin/openPanel",
    pluginThemes: "pi-desktop/plugin/themes",
    pluginServices: "pi-desktop/plugin/services",
    marketRefresh: "pi-desktop/market/refresh",
    marketSearch: "pi-desktop/market/search",
    marketGetDetail: "pi-desktop/market/getDetail",
    marketInstall: "pi-desktop/market/install",
    marketCheckUpdates: "pi-desktop/market/checkUpdates",
    marketApplyUpdates: "pi-desktop/market/applyUpdates",
    commandPaletteSearch: "pi-desktop/commandPalette/search",
    commandPaletteExecute: "pi-desktop/commandPalette/execute",
    logOpenFolder: "pi-desktop/log/openFolder",
    devtoolsToggle: "pi-desktop/devtools/toggle",
    composerPickFiles: "pi-desktop/composer/pickFiles",
    composerPickPhotos: "pi-desktop/composer/pickPhotos",
    composerCommands: "pi-desktop/composer/commands",
    workspaceDiff: "pi-desktop/workspace/diff",
    terminalCreate: "pi-desktop/terminal/create",
    terminalWrite: "pi-desktop/terminal/write",
    terminalResize: "pi-desktop/terminal/resize",
    terminalDispose: "pi-desktop/terminal/dispose",
    browserNavigate: "pi-desktop/browser/navigate",
    browserAction: "pi-desktop/browser/action",
    browserSetBounds: "pi-desktop/browser/setBounds",
    browserSetVisible: "pi-desktop/browser/setVisible",
    browserOpenExternal: "pi-desktop/browser/openExternal",
    browserGetState: "pi-desktop/browser/getState",
    fsList: "pi-desktop/fs/list",
    fsRead: "pi-desktop/fs/read",
    fsReveal: "pi-desktop/fs/reveal",
    fsIndex: "pi-desktop/fs/index",
    windowSetWorkPanelReservation:
      "pi-desktop/window/setWorkPanelReservation",
    windowControl: "pi-desktop/window/control",
    menuRendererReady: "pi-desktop/menu/rendererReady",
    nativeMenuAction: "pi-desktop/menu/nativeAction",
  },
  event: {
    pluginChanged: "pi-desktop/event/pluginChanged",
    agentMessage: "pi-desktop/agent/event/message",
    hostStatus: "pi-desktop/app/event/hostStatus",
    toast: "pi-desktop/app/event/toast",
    terminalData: "pi-desktop/terminal/event/data",
    terminalExit: "pi-desktop/terminal/event/exit",
    browserState: "pi-desktop/browser/event/state",
    browserPreview: "pi-desktop/browser/event/preview",
    windowMaximized: "pi-desktop/window/event/maximized",
    windowFullScreen: "pi-desktop/window/event/fullscreen",
    menuCommand: "pi-desktop/menu/event/command",
    notificationChanged: "pi-desktop/notification/event/changed",
    notificationActivated: "pi-desktop/notification/event/activated",
    updatesState: "pi-desktop/updates/event/state",
  },
} as const;

export const IPC_WHITELIST = new Set<string>([
  ...Object.values(IPC.invoke),
  ...Object.values(IPC.event),
]);
