/**
 * The skill catalog that ships inside the app.
 *
 * Every entry is a real, live markdown document (currently from
 * anthropics/skills, Apache-2.0) so the market is useful before any remote
 * source exists. Custom catalog sources layer on top; this stays the offline
 * floor.
 */
import type { SkillCatalogFile } from "./skill-catalog.js";

const ANTHROPIC = "https://raw.githubusercontent.com/anthropics/skills/main/skills";
const homepageFor = (slug: string) => `https://github.com/anthropics/skills/tree/main/skills/${slug}`;

export const BUILTIN_SKILL_CATALOG: SkillCatalogFile = {
  schemaVersion: 1,
  updatedAt: "2026-09-12",
  source: "builtin",
  skills: [
    {
      id: "docx",
      name: "Word 文档",
      description: "创建、读取、编辑 Word (.docx) 文档,支持修订与批注",
      author: "anthropic",
      homepage: homepageFor("docx"),
      url: `${ANTHROPIC}/docx/SKILL.md`,
      categories: ["docs"],
      verified: true,
    },
    {
      id: "pdf",
      name: "PDF 处理",
      description: "读取、提取、合并、拆分与生成 PDF 文件",
      author: "anthropic",
      homepage: homepageFor("pdf"),
      categories: ["docs"],
      verified: true,
      url: `${ANTHROPIC}/pdf/SKILL.md`,
    },
    {
      id: "pptx",
      name: "PPT 演示文稿",
      description: "创建、编辑与分析 PowerPoint (.pptx) 演示文稿",
      author: "anthropic",
      homepage: homepageFor("pptx"),
      categories: ["docs"],
      verified: true,
      url: `${ANTHROPIC}/pptx/SKILL.md`,
    },
    {
      id: "xlsx",
      name: "Excel 表格",
      description: "处理电子表格:公式、图表、数据透视与多工作表",
      author: "anthropic",
      homepage: homepageFor("xlsx"),
      categories: ["docs", "data"],
      verified: true,
      url: `${ANTHROPIC}/xlsx/SKILL.md`,
    },
    {
      id: "frontend-design",
      name: "Frontend Design",
      description: "构建或重塑 UI 时做出有辨识度、有意图的视觉设计",
      author: "anthropic",
      homepage: homepageFor("frontend-design"),
      categories: ["coding"],
      verified: true,
      url: `${ANTHROPIC}/frontend-design/SKILL.md`,
    },
    {
      id: "web-artifacts-builder",
      name: "Web Artifacts Builder",
      description: "用现代前端技术构建复杂的多组件 HTML 产物",
      author: "anthropic",
      homepage: homepageFor("web-artifacts-builder"),
      categories: ["coding"],
      verified: true,
      url: `${ANTHROPIC}/web-artifacts-builder/SKILL.md`,
    },
    {
      id: "webapp-testing",
      name: "Webapp Testing",
      description: "用 Playwright 与本地 Web 应用交互并验证前端行为",
      author: "anthropic",
      homepage: homepageFor("webapp-testing"),
      categories: ["coding"],
      verified: true,
      url: `${ANTHROPIC}/webapp-testing/SKILL.md`,
    },
    {
      id: "mcp-builder",
      name: "MCP Builder",
      description: "创建高质量的 MCP 服务器,让 LLM 对接外部工具与数据",
      author: "anthropic",
      homepage: homepageFor("mcp-builder"),
      categories: ["coding"],
      verified: true,
      url: `${ANTHROPIC}/mcp-builder/SKILL.md`,
    },
    {
      id: "skill-creator",
      name: "Skill Creator",
      description: "创建新技能、改进现有技能并度量技能效果",
      author: "anthropic",
      homepage: homepageFor("skill-creator"),
      categories: ["coding", "workflow"],
      verified: true,
      url: `${ANTHROPIC}/skill-creator/SKILL.md`,
    },
    {
      id: "claude-api",
      name: "Claude API",
      description: "Claude API 与 SDK 的最佳实践参考",
      author: "anthropic",
      homepage: homepageFor("claude-api"),
      categories: ["coding"],
      verified: true,
      url: `${ANTHROPIC}/claude-api/SKILL.md`,
    },
    {
      id: "doc-coauthoring",
      name: "Doc Coauthoring",
      description: "结构化流程协同创作文档,从大纲到成稿",
      author: "anthropic",
      homepage: homepageFor("doc-coauthoring"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/doc-coauthoring/SKILL.md`,
    },
    {
      id: "internal-comms",
      name: "Internal Comms",
      description: "按公司惯用格式撰写各类内部通讯与公告",
      author: "anthropic",
      homepage: homepageFor("internal-comms"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/internal-comms/SKILL.md`,
    },
    {
      id: "algorithmic-art",
      name: "Algorithmic Art",
      description: "用 p5.js 创作算法艺术,支持种子随机与交互参数",
      author: "anthropic",
      homepage: homepageFor("algorithmic-art"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/algorithmic-art/SKILL.md`,
    },
    {
      id: "canvas-design",
      name: "Canvas Design",
      description: "以设计哲学产出 .png/.pdf 视觉作品",
      author: "anthropic",
      homepage: homepageFor("canvas-design"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/canvas-design/SKILL.md`,
    },
    {
      id: "theme-factory",
      name: "Theme Factory",
      description: "为幻灯、文档、报告与落地页套用主题样式",
      author: "anthropic",
      homepage: homepageFor("theme-factory"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/theme-factory/SKILL.md`,
    },
    {
      id: "slack-gif-creator",
      name: "Slack GIF Creator",
      description: "制作适配 Slack 约束的动画 GIF",
      author: "anthropic",
      homepage: homepageFor("slack-gif-creator"),
      categories: ["writing"],
      verified: true,
      url: `${ANTHROPIC}/slack-gif-creator/SKILL.md`,
    },
    {
      id: "brand-guidelines",
      name: "Brand Guidelines",
      description: "把 Anthropic 官方品牌色与字体规范应用到产物上",
      author: "anthropic",
      homepage: homepageFor("brand-guidelines"),
      categories: ["docs"],
      verified: true,
      url: `${ANTHROPIC}/brand-guidelines/SKILL.md`,
    },
    {
      id: "academy-guide",
      name: "Academy Guide",
      description: "Claude 学院使用指南",
      author: "anthropic",
      homepage: homepageFor("academy-guide"),
      categories: ["workflow"],
      verified: true,
      url: `${ANTHROPIC}/academy-guide/SKILL.md`,
    },
    {
      id: "discernment-nudge",
      name: "Discernment Nudge",
      description: "在动手前先甄别请求意图的提示技能",
      author: "anthropic",
      homepage: homepageFor("discernment-nudge"),
      categories: ["workflow"],
      verified: true,
      url: `${ANTHROPIC}/discernment-nudge/SKILL.md`,
    },
  ],
};
