import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const IMPORTED_PLUGIN_ID_PREFIX = "imported.";
export const IMPORTED_PLUGIN_MAIN = "main.cjs";
export const LEGACY_IMPORTED_PLUGIN_MAIN = "main.js";
export const IMPORTED_PLUGIN_WRAPPER_SOURCE =
  "// Generated by PI-Desktop: declarative skills and/or agent extensions.\nmodule.exports = {};\n";

function isGeneratedImportedWrapper(source: string): boolean {
  const normalized = source.replace(/\r\n/g, "\n");
  return /^\/\/ Generated by PI-Desktop:.*\nmodule\.exports = \{\};\n$/.test(normalized);
}

/**
 * Rewrite a pre-`main.cjs` imported plugin wrapper in place (spec 16 §3.2).
 * Only the generated no-op is touched; copied package files stay as they are.
 */
export function repairImportedExtensionWrapper(pluginPath: string): boolean {
  const manifestPath = join(pluginPath, "manifest.json");
  if (!existsSync(manifestPath)) return false;
  let manifest: Record<string, unknown>;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>;
  } catch {
    return false;
  }
  if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) return false;
  if (typeof manifest.id !== "string" || !manifest.id.startsWith(IMPORTED_PLUGIN_ID_PREFIX)) {
    return false;
  }
  if (manifest.main !== LEGACY_IMPORTED_PLUGIN_MAIN) return false;

  const legacyPath = join(pluginPath, LEGACY_IMPORTED_PLUGIN_MAIN);
  const nextPath = join(pluginPath, IMPORTED_PLUGIN_MAIN);
  if (!existsSync(legacyPath)) return false;
  if (!isGeneratedImportedWrapper(readFileSync(legacyPath, "utf8"))) return false;
  if (existsSync(nextPath) && !isGeneratedImportedWrapper(readFileSync(nextPath, "utf8"))) {
    return false;
  }

  writeFileSync(nextPath, IMPORTED_PLUGIN_WRAPPER_SOURCE, "utf8");
  writeFileSync(
    manifestPath,
    `${JSON.stringify({ ...manifest, main: IMPORTED_PLUGIN_MAIN }, null, 2)}\n`,
    "utf8",
  );
  unlinkSync(legacyPath);
  return true;
}
